#!/bin/env sh

# Default options for programs' aliases
LS_DEFAULT_OPTIONS="--group-directories-first --color=always"
GREP_DEFAULT_OPTIONS="--color=always"

# Nvim aliase
alias nvim="nvim -n"

# Aliases for ls and exa commands
alias ls="ls ${LS_DEFAULT_OPTIONS}"
alias la="ls -A ${LS_DEFAULT_OPTIONS}"
alias ll="ls -Alh ${LS_DEFAULT_OPTIONS}"
alias exa="exa ${EXA_DEFAULT_OPTIONS}"

alias tmux="tmux -f ~/.config/tmux/tmux.conf"

# Alias for "grep" command
alias grep="grep $GREP_DEFAULT_OPTIONS"

# Alias for massive renaming
alias bulk-rename="qmv -f do"

# Alias for showing time
alias dtime="date +\"%R:%S\""

alias p="mplayer"
alias i="sxiv"
alias e="nvim"

# Never gonna give you up!~
alias rr="rickroll"

# Aliases for openrc-init
#alias reboot="sudo openrc-shutdown -r now"
#alias halt="sudo openrc-shutdown -H now"
#alias shutdown="sudo openrc-shutdown"
#alias poweroff="sudo openrc-shutdown -p now"
